[2023-01-20T17:01:49.753-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: bronze_opt_t_conta.run_databricks_notebook manual__2023-01-20T20:01:41.474423+00:00 [queued]>
[2023-01-20T17:01:50.129-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: bronze_opt_t_conta.run_databricks_notebook manual__2023-01-20T20:01:41.474423+00:00 [queued]>
[2023-01-20T17:01:50.129-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-20T17:01:50.129-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-20T17:01:50.129-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-20T17:01:50.604-0300] {taskinstance.py:1304} INFO - Executing <Task(DatabricksSubmitRunOperator): run_databricks_notebook> on 2023-01-20 20:01:41.474423+00:00
[2023-01-20T17:01:50.609-0300] {standard_task_runner.py:55} INFO - Started process 655504 to run task
[2023-01-20T17:01:50.613-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'bronze_opt_t_conta', 'run_databricks_notebook', 'manual__2023-01-20T20:01:41.474423+00:00', '--job-id', '1081', '--raw', '--subdir', 'DAGS_FOLDER/bronze/dock_opt/bronze_opt_t_conta.py', '--cfg-path', '/tmp/tmp9sc5mm73']
[2023-01-20T17:01:50.616-0300] {standard_task_runner.py:83} INFO - Job 1081: Subtask run_databricks_notebook
[2023-01-20T17:01:53.668-0300] {task_command.py:389} INFO - Running <TaskInstance: bronze_opt_t_conta.run_databricks_notebook manual__2023-01-20T20:01:41.474423+00:00 [running]> on host vm-airflow-01
[2023-01-20T17:01:56.090-0300] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=matheus.rodrigues@fortbrasil.com.br
AIRFLOW_CTX_DAG_ID=bronze_opt_t_conta
AIRFLOW_CTX_TASK_ID=run_databricks_notebook
AIRFLOW_CTX_EXECUTION_DATE=2023-01-20T20:01:41.474423+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-20T20:01:41.474423+00:00
[2023-01-20T17:01:56.587-0300] {base.py:73} INFO - Using connection ID 'adb' for task execution.
[2023-01-20T17:01:56.777-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-20T17:01:58.065-0300] {databricks.py:50} INFO - Run submitted with run_id: 62145
[2023-01-20T17:01:58.066-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-20T17:01:59.206-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-20T17:01:59.543-0300] {databricks.py:91} INFO - run_databricks_notebook in run state: {'life_cycle_state': 'PENDING', 'result_state': '', 'state_message': ''}
[2023-01-20T17:01:59.543-0300] {databricks.py:92} INFO - View run status, Spark UI, and logs at https://adb-1362567168960874.14.azuredatabricks.net/?o=1362567168960874#job/717727016004889/run/62145
[2023-01-20T17:01:59.543-0300] {databricks.py:93} INFO - Sleeping for 30 seconds.
[2023-01-20T17:02:29.574-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-20T17:02:29.915-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-20T17:02:30.897-0300] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/databricks/operators/databricks.py", line 376, in execute
    _handle_databricks_operator_execution(self, self._hook, self.log, context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/databricks/operators/databricks.py", line 88, in _handle_databricks_operator_execution
    raise AirflowException(error_message)
airflow.exceptions.AirflowException: run_databricks_notebook failed with terminal state: {'life_cycle_state': 'TERMINATED', 'result_state': 'FAILED', 'state_message': ''} and with the error java.io.FileNotFoundException: File /1362567168960874/mnt/dock_opt/t_conta does not exist.
[2023-01-20T17:02:31.017-0300] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=bronze_opt_t_conta, task_id=run_databricks_notebook, execution_date=20230120T200141, start_date=20230120T200149, end_date=20230120T200231
[2023-01-20T17:02:31.658-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 1081 for task run_databricks_notebook (run_databricks_notebook failed with terminal state: {'life_cycle_state': 'TERMINATED', 'result_state': 'FAILED', 'state_message': ''} and with the error java.io.FileNotFoundException: File /1362567168960874/mnt/dock_opt/t_conta does not exist.; 655504)
[2023-01-20T17:02:31.687-0300] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-20T17:02:32.446-0300] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
