[2023-01-20T16:58:03.483-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: bronze_opt_t_conta.run_databricks_notebook manual__2023-01-20T19:57:54.402700+00:00 [queued]>
[2023-01-20T16:58:03.850-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: bronze_opt_t_conta.run_databricks_notebook manual__2023-01-20T19:57:54.402700+00:00 [queued]>
[2023-01-20T16:58:03.850-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-20T16:58:03.851-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-20T16:58:03.851-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-20T16:58:04.249-0300] {taskinstance.py:1304} INFO - Executing <Task(DatabricksSubmitRunOperator): run_databricks_notebook> on 2023-01-20 19:57:54.402700+00:00
[2023-01-20T16:58:04.254-0300] {standard_task_runner.py:55} INFO - Started process 654895 to run task
[2023-01-20T16:58:04.258-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'bronze_opt_t_conta', 'run_databricks_notebook', 'manual__2023-01-20T19:57:54.402700+00:00', '--job-id', '1080', '--raw', '--subdir', 'DAGS_FOLDER/bronze/dock_opt/bronze_opt_t_conta.py', '--cfg-path', '/tmp/tmpmnwff28i']
[2023-01-20T16:58:04.261-0300] {standard_task_runner.py:83} INFO - Job 1080: Subtask run_databricks_notebook
[2023-01-20T16:58:07.239-0300] {task_command.py:389} INFO - Running <TaskInstance: bronze_opt_t_conta.run_databricks_notebook manual__2023-01-20T19:57:54.402700+00:00 [running]> on host vm-airflow-01
[2023-01-20T16:58:09.737-0300] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=matheus.rodrigues@fortbrasil.com.br
AIRFLOW_CTX_DAG_ID=bronze_opt_t_conta
AIRFLOW_CTX_TASK_ID=run_databricks_notebook
AIRFLOW_CTX_EXECUTION_DATE=2023-01-20T19:57:54.402700+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-20T19:57:54.402700+00:00
[2023-01-20T16:58:10.273-0300] {base.py:73} INFO - Using connection ID 'adb' for task execution.
[2023-01-20T16:58:10.465-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-20T16:58:11.880-0300] {databricks.py:50} INFO - Run submitted with run_id: 61606
[2023-01-20T16:58:11.881-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-20T16:58:13.047-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-20T16:58:13.402-0300] {databricks.py:91} INFO - run_databricks_notebook in run state: {'life_cycle_state': 'PENDING', 'result_state': '', 'state_message': ''}
[2023-01-20T16:58:13.402-0300] {databricks.py:92} INFO - View run status, Spark UI, and logs at https://adb-1362567168960874.14.azuredatabricks.net/?o=1362567168960874#job/364158043573898/run/61606
[2023-01-20T16:58:13.402-0300] {databricks.py:93} INFO - Sleeping for 30 seconds.
[2023-01-20T16:58:43.417-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-20T16:58:43.760-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-20T16:58:45.172-0300] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/databricks/operators/databricks.py", line 376, in execute
    _handle_databricks_operator_execution(self, self._hook, self.log, context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/databricks/operators/databricks.py", line 88, in _handle_databricks_operator_execution
    raise AirflowException(error_message)
airflow.exceptions.AirflowException: run_databricks_notebook failed with terminal state: {'life_cycle_state': 'TERMINATED', 'result_state': 'FAILED', 'state_message': ''} and with the error Failure to initialize configurationInvalid configuration value detected for fs.azure.account.key
[2023-01-20T16:58:45.265-0300] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=bronze_opt_t_conta, task_id=run_databricks_notebook, execution_date=20230120T195754, start_date=20230120T195803, end_date=20230120T195845
[2023-01-20T16:58:45.837-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 1080 for task run_databricks_notebook (run_databricks_notebook failed with terminal state: {'life_cycle_state': 'TERMINATED', 'result_state': 'FAILED', 'state_message': ''} and with the error Failure to initialize configurationInvalid configuration value detected for fs.azure.account.key; 654895)
[2023-01-20T16:58:45.878-0300] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-20T16:58:46.450-0300] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
