[2023-01-23T11:18:16.233-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: raw_opt_t_fatura.get_last_date manual__2023-01-23T14:17:43.025899+00:00 [queued]>
[2023-01-23T11:18:16.855-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: raw_opt_t_fatura.get_last_date manual__2023-01-23T14:17:43.025899+00:00 [queued]>
[2023-01-23T11:18:16.855-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-23T11:18:16.856-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-23T11:18:16.856-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-23T11:18:17.242-0300] {taskinstance.py:1304} INFO - Executing <Task(DatabricksSubmitRunOperator): get_last_date> on 2023-01-23 14:17:43.025899+00:00
[2023-01-23T11:18:17.248-0300] {standard_task_runner.py:55} INFO - Started process 1101751 to run task
[2023-01-23T11:18:17.252-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'raw_opt_t_fatura', 'get_last_date', 'manual__2023-01-23T14:17:43.025899+00:00', '--job-id', '1174', '--raw', '--subdir', 'DAGS_FOLDER/raw/dock_opt/raw_opt_t_fatura.py', '--cfg-path', '/tmp/tmpz6vmoc_x']
[2023-01-23T11:18:17.255-0300] {standard_task_runner.py:83} INFO - Job 1174: Subtask get_last_date
[2023-01-23T11:18:24.727-0300] {task_command.py:389} INFO - Running <TaskInstance: raw_opt_t_fatura.get_last_date manual__2023-01-23T14:17:43.025899+00:00 [running]> on host vm-airflow-01
[2023-01-23T11:18:27.301-0300] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=matheus.rodrigues@fortbrasil.com.br
AIRFLOW_CTX_DAG_ID=raw_opt_t_fatura
AIRFLOW_CTX_TASK_ID=get_last_date
AIRFLOW_CTX_EXECUTION_DATE=2023-01-23T14:17:43.025899+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-23T14:17:43.025899+00:00
[2023-01-23T11:18:27.830-0300] {base.py:73} INFO - Using connection ID 'adb' for task execution.
[2023-01-23T11:18:28.015-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-23T11:18:29.393-0300] {databricks.py:50} INFO - Run submitted with run_id: 71422
[2023-01-23T11:18:29.393-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-23T11:18:30.415-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-23T11:18:30.779-0300] {databricks.py:91} INFO - get_last_date in run state: {'life_cycle_state': 'PENDING', 'result_state': '', 'state_message': ''}
[2023-01-23T11:18:30.780-0300] {databricks.py:92} INFO - View run status, Spark UI, and logs at https://adb-1362567168960874.14.azuredatabricks.net/?o=1362567168960874#job/569342455543478/run/71422
[2023-01-23T11:18:30.780-0300] {databricks.py:93} INFO - Sleeping for 30 seconds.
[2023-01-23T11:19:00.811-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-23T11:19:02.327-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-23T11:19:03.271-0300] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/databricks/operators/databricks.py", line 376, in execute
    _handle_databricks_operator_execution(self, self._hook, self.log, context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/databricks/operators/databricks.py", line 88, in _handle_databricks_operator_execution
    raise AirflowException(error_message)
airflow.exceptions.AirflowException: get_last_date failed with terminal state: {'life_cycle_state': 'TERMINATED', 'result_state': 'FAILED', 'state_message': ''} and with the error py4j.security.Py4JSecurityException: Method public boolean org.apache.spark.sql.internal.CatalogImpl.tableExists(java.lang.String) is not whitelisted on class class org.apache.spark.sql.internal.CatalogImpl
[2023-01-23T11:19:03.368-0300] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=raw_opt_t_fatura, task_id=get_last_date, execution_date=20230123T141743, start_date=20230123T141816, end_date=20230123T141903
[2023-01-23T11:19:03.938-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 1174 for task get_last_date (get_last_date failed with terminal state: {'life_cycle_state': 'TERMINATED', 'result_state': 'FAILED', 'state_message': ''} and with the error py4j.security.Py4JSecurityException: Method public boolean org.apache.spark.sql.internal.CatalogImpl.tableExists(java.lang.String) is not whitelisted on class class org.apache.spark.sql.internal.CatalogImpl; 1101751)
[2023-01-23T11:19:05.468-0300] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-23T11:19:06.183-0300] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
