[2023-01-23T11:48:42.547-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: raw_opt_t_fatura.get_last_date manual__2023-01-23T14:48:15.247764+00:00 [queued]>
[2023-01-23T11:48:43.428-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: raw_opt_t_fatura.get_last_date manual__2023-01-23T14:48:15.247764+00:00 [queued]>
[2023-01-23T11:48:43.429-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-23T11:48:43.429-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-23T11:48:43.429-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-23T11:48:43.919-0300] {taskinstance.py:1304} INFO - Executing <Task(DatabricksSubmitRunOperator): get_last_date> on 2023-01-23 14:48:15.247764+00:00
[2023-01-23T11:48:43.925-0300] {standard_task_runner.py:55} INFO - Started process 1106588 to run task
[2023-01-23T11:48:43.929-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'raw_opt_t_fatura', 'get_last_date', 'manual__2023-01-23T14:48:15.247764+00:00', '--job-id', '1176', '--raw', '--subdir', 'DAGS_FOLDER/raw/dock_opt/raw_opt_t_fatura.py', '--cfg-path', '/tmp/tmpf2ds595a']
[2023-01-23T11:48:43.933-0300] {standard_task_runner.py:83} INFO - Job 1176: Subtask get_last_date
[2023-01-23T11:48:47.060-0300] {task_command.py:389} INFO - Running <TaskInstance: raw_opt_t_fatura.get_last_date manual__2023-01-23T14:48:15.247764+00:00 [running]> on host vm-airflow-01
[2023-01-23T11:48:49.658-0300] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=matheus.rodrigues@fortbrasil.com.br
AIRFLOW_CTX_DAG_ID=raw_opt_t_fatura
AIRFLOW_CTX_TASK_ID=get_last_date
AIRFLOW_CTX_EXECUTION_DATE=2023-01-23T14:48:15.247764+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-23T14:48:15.247764+00:00
[2023-01-23T11:48:50.219-0300] {base.py:73} INFO - Using connection ID 'adb' for task execution.
[2023-01-23T11:48:50.448-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-23T11:48:55.685-0300] {databricks.py:50} INFO - Run submitted with run_id: 71704
[2023-01-23T11:48:55.686-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-23T11:48:56.810-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-23T11:48:57.165-0300] {databricks.py:91} INFO - get_last_date in run state: {'life_cycle_state': 'RUNNING', 'result_state': '', 'state_message': 'In run'}
[2023-01-23T11:48:57.166-0300] {databricks.py:92} INFO - View run status, Spark UI, and logs at https://adb-1362567168960874.14.azuredatabricks.net/?o=1362567168960874#job/506613649025987/run/71704
[2023-01-23T11:48:57.166-0300] {databricks.py:93} INFO - Sleeping for 30 seconds.
[2023-01-23T11:49:27.180-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-23T11:49:27.522-0300] {databricks_base.py:424} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2023-01-23T11:49:28.486-0300] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/databricks/operators/databricks.py", line 376, in execute
    _handle_databricks_operator_execution(self, self._hook, self.log, context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/databricks/operators/databricks.py", line 88, in _handle_databricks_operator_execution
    raise AirflowException(error_message)
airflow.exceptions.AirflowException: get_last_date failed with terminal state: {'life_cycle_state': 'TERMINATED', 'result_state': 'FAILED', 'state_message': ''} and with the error py4j.security.Py4JSecurityException: Method public boolean org.apache.spark.sql.internal.CatalogImpl.tableExists(java.lang.String) is not whitelisted on class class org.apache.spark.sql.internal.CatalogImpl
[2023-01-23T11:49:28.579-0300] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=raw_opt_t_fatura, task_id=get_last_date, execution_date=20230123T144815, start_date=20230123T144842, end_date=20230123T144928
[2023-01-23T11:49:29.132-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 1176 for task get_last_date (get_last_date failed with terminal state: {'life_cycle_state': 'TERMINATED', 'result_state': 'FAILED', 'state_message': ''} and with the error py4j.security.Py4JSecurityException: Method public boolean org.apache.spark.sql.internal.CatalogImpl.tableExists(java.lang.String) is not whitelisted on class class org.apache.spark.sql.internal.CatalogImpl; 1106588)
[2023-01-23T11:49:30.655-0300] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-23T11:49:31.371-0300] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
